name: OWASP Dependency Check

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  dependency-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            owasp/dependency-check \
            --project "bp" \
            --scan /src \
            --format "HTML" \
            --out /src/dependency-check-report

      - name: Archive OWASP Report
        run: |
         zip -r dependency-check-report.zip dependency-check-report

      - name: Display OWASP Report Path
        run: |
         echo "Report archived at ${{ github.workspace }}/dependency-check-report.zip"