name: OWASP Dependency Check

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check via Docker
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -e NVD_API_KEY=$NVD_API_KEY \
            owasp/dependency-check \
            --project "bp" \
            --scan /src/BPCalculator \
            --format "HTML" \
            --out /src/dependency-check-report \
            --failOnCVSS 11

      - name: Archive OWASP Report
        run: |
          zip -r dependency-check-report.zip dependency-check-report

      - name: Echo OWASP Report Path
        run: |
          echo "Report is at ${{ github.workspace }}/dependency-check-report.zip"